### PR TITLE
Add URL remote

### PR DESCRIPTION
**Pull request by rominf**
I tested it with simple project: https://github.com/rominf/lazydata_test

### CODE REVIEW

**Comment by rstojnic** [comment]
@rominf Awesome! I'm travelling this whole week, but as soon as I'm back I'll review and merge. Looks good looking at it quickly now!

**Comment by rstojnic** [comment]
It looks good, I've just added the smart download library to setup.py as well so it gets installed with the package in f321d9aa226ba8bcccac8982cc1e635d76550372.

**Comment by rominf** [comment]
@rstojnic, thank you for merging! Sorry, forgot to add to `setup.py` myself.

**Comment by rstojnic** [comment]
@rominf no worries - this is awesome work!!

**Pull request merged**
