### PR TITLE
Adding support for custom endpoint

### PR DESCRIPTION
**Pull request by zbitouzakaria**
Useful for users that do not want to rely on Amazon S3 while using this package.

I'm running a [Minio Server](https://github.com/minio/minio) for storage, which mimics an S3 container.

boto3 ([api doc here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client)) supports custom endpoints that it's going to hit via the S3 API.

I would be good to add tests to this behaviour, along with testing pulls and pushes for normal behaviour. Using mocks maybe ?

EDIT: I also corrected a line which caused the package not to work for python 3.5, see commit 
0d4f8fc

### CODE REVIEW

**Comment by varun19299** [comment]
Could you list the changes in the `add-remote` command for a minio server?

**Comment by zbitouzakaria** [comment]
@varun19299 It's automatically done thanks to `argparse`. There is an additional optional parameter `--endpoint-url [ENDPOINT_URL]` which can be set to your custom URL. Here is the new usage:

```
usage: lazydata add-remote [-h] [--endpoint-url [ENDPOINT_URL]] url

positional arguments:
  url                   URL of the remote storage backend

optional arguments:
  -h, --help            show this help message and exit
  --endpoint-url [ENDPOINT_URL]
                        The complete URL to use for the constructed client
```

**Comment by rstojnic** [comment]
Thanks @zbitouzakaria this looks good! Yes, adding some test cases for mocked S3 would be amazing. If you don't have time to add the test cases, just give me some time to test it and I'll merge.

**Comment by varun19299** [comment]
Sure, I'll try that out. I'm trying to setup a private NFS like system for storing weights (training files) . Hopefully, this and `minio` should work out. Any ideas if you're using a similar implementation?

**Comment by zbitouzakaria** [comment]
@varun19299 Just use it the same way as you would normally. But at the `add_remote` stage, instead of executing this:
```
lazydata add-remote s3://mybucket/lazydata
```
Use this instead
```
lazydata add-remote s3://mybucket/lazydata --endpoint-url http://127.0.0.1:9000
```
Where:
* `mybucket` is the name of your minio bucket (everything is in their docs about bucket creation)
* `lazydata` would be a directory inside this bucket (gets automatically created)
* Your endpoint URL would be what the minio server returns when you launch it. Could be any other IP address

Don't forget to also set up your credentials as you would for AWS. Minio provides an API and secret key. Everything is working nicely on my end!

@rstojnic I don't know if i'll have the time to setup tests before next week. I'll get back to you on that :)

**Comment by rstojnic** [comment]
LGTM, will merge now. Will need to add tests for this and other remotes in the future!

**Pull request merged**
